# Generated by Django 2.1 on 2019-02-19 14:56

from django.db import migrations, models
import posts.models


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0005_auto_20190219_1437'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='image',
            field=models.ImageField(blank=True, height_field='height_field', null=True, upload_to=posts.models.upload_location, verbose_name='Imagen', width_field='width_field'),
        ),
    ]
